language: php

php:
  - 7
  - hhvm

before_script:
  - composer update
  - git clone https://github.com/padraic/humbug.git && cd humbug && composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs
  - ./humbug/bin/humbug
  - ./build/check-humbug-mutators.php

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
