language: php

php:
  - 7
  - hhvm

before_script:
  - composer update
  - if [ "$DEPENDENCIES" = 'low' ] ; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - git clone https://github.com/padraic/humbug.git && cd humbug && composer install && cd ..

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs
  - ./humbug/bin/humbug
  - ./build/check-humbug-mutators.php

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
