language: php

php:
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer update
  - if [ "$DEPENDENCIES" = 'low' ] ; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - git clone https://github.com/padraic/humbug.git && cd humbug && composer install && cd ..

script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then PHPUNIT_FLAGS="--coverage-clover ./clover.xml"; else PHPUNIT_FLAGS=""; fi
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS
  - ./vendor/bin/phpcs
  - ./humbug/bin/humbug
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then ./vendor/bin/humbug; fi
  - cd examples
  - composer install
  - php index.php > /dev/null

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ -f clover.xml ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
